###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  postgres:
    build: codeInfrastructure/phpdocker/pgsql
    working_dir: /var/www
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/www
      - ./codeInfrastructure/pgsql/data:/var/lib/postgresql/data/pgdata/
    ports:
      - "4132:5432"


  webserver:
    image: nginx:alpine
    container_name: $APP_NAME-webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./codeInfrastructure/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $WEBSERVER_PORT:80
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"


  php-fpm:
    build: codeInfrastructure/phpdocker/php-fpm
    container_name: $APP_NAME-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - ./codeInfrastructure/phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./codeInfrastructure/phpdocker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    environment:
      - PHP_IDE_CONFIG=serverName=xdebugserver


  php-fpm-cli:
    build:
      context: codeInfrastructure/phpdocker/php-fpm/cli
      dockerfile: Dockerfile
    container_name: $APP_NAME-php-fpm-cli
#    user: "1000:1000"
    working_dir: /var/www
    volumes:
      - .:/var/www:cached






