POST http://localhost:4190/api/login_check
Content-Type: application/json

{"username":"test@test.test","password":"123456789"}

###

GET http://localhost:4190/api/page
Authorization: Bearer wrongtoken
Accept: application/json

###

GET http://localhost:4190/api/page
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjI5Nzc5MTksImV4cCI6MTExMjM3Nzc5MTksInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC50ZXN0In0.hbVYsG--PGO_JSJZp9tCYMW3j89AXwoHub9SXPnAMG2I5FIJzjIxLCUxYr6NHx3itZsMWGXLY-jO3v-dj2hYNQf-e3zYP2Yd27IJ4BSnMRS7dxKq3IJjTb-krVpOsFNUZr1Pe0OB8N5Kf4h7d_1Dq_1ftzS8eGWr90ySxtZlSb44TkQEAncdw9l7SMZtONM7KqI3kOERQE7tskFajP9RwKdhrTnVeKIXdIzC_OIyvjLrGBRfpAYiDx5gC8Ch9C8h-Av33lrwbENYSIU4x-oorQpWneDHIm7PIyh2T_NKVKRY742Vy9TZX1PnTrBdWUQRSWOX80v1xPHCMTNlLy0w7A
Accept: application/json

###